In [1]:
import numpy as np

stock1 = np.array([
    [100, 105, 98],
    [102, 107, 99],
    [101, 106, 97],
    [103, 108, 100],
    [104, 109, 101]
])

stock2 = np.array([
    [98, 103, 95],
    [100, 105, 97],
    [99, 104, 96],
    [101, 106, 98],
    [102, 107, 99]
])

sum_matrix = stock1 + stock2
diff_matrix = stock1 - stock2

print("Element-wise Sum of Stock Prices:\n", sum_matrix)
print("\nElement-wise Difference of Stock Prices:\n", diff_matrix)

Element-wise Sum of Stock Prices:
 [[198 208 193]
 [202 212 196]
 [200 210 193]
 [204 214 198]
 [206 216 200]]

Element-wise Difference of Stock Prices:
 [[2 2 3]
 [2 2 2]
 [2 2 1]
 [2 2 2]
 [2 2 2]]
